### ISSUE TITLE
add fried rice recipe

### ISSUE THREAD

**Issue by prachitim** [openpaul/cookbook#3]
1. Heat @oil{2%tbsp} in a @wok{}.
2. Add chopped @onions{1} and @garlic{3}, stir-fry until golden brown.
3. Toss in diced @carrots{150%g} and @peas{100%g}, stir for a few minutes.
4. Push veggies to the side, add @eggs{2} and scramble.
5. Mix in pre-cooked @rice{300%g}, ensuring it's well combined.
6. Season with @soy sauce{3%tbsp} and sprinkle with chopped @spring onions{}.
7. Stir thoroughly and cook for an additional 5 minutes.
8. Serve hot and enjoy!

**This recipe was AI generated**

**Comment by openpaul** [comment]
thank you. Done with commit https://github.com/openpaul/cookbook/commit/860c738542a1513d8422d930dbf6082c12da0413
